---
config:
    layout: elk
---
flowchart LR
    head(("Head<br>Snapshot"))
    subgraph Entries
        n1["n"]@{ shape: sm-circ }
        n2["n+1"]@{ shape: sm-circ }
        m1["m-1"]@{ shape: sm-circ }
        m2["m"]@{ shape: sm-circ }
    end
    tail(("Tail<br>Snapshot"))
    head --- n1
    m2 --- tail
    n1 --> n2
    m1 --> m2
    n2 -- " ... " --> m1
